wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714525322.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
